- name: Push Nginx virtual host configuration
  ansible.builtin.copy:
    src: matpohj.fi
    dest: /etc/nginx/sites-available/matpohj.fi
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Enable Nginx virtual host
  ansible.builtin.file:
    src: /etc/nginx/sites-available/matpohj.fi
    dest: /etc/nginx/sites-enabled/matpohj.fi
    state: link
  notify: Restart Nginx

- name: Remove default Nginx virtual host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx
