- name: Provision and Harden VPS
  hosts: all
  become: yes # This tells Ansible to use 'sudo' to escalate privileges
  roles:
    - { role: hardening, tags: ['hardening'] }
    - { role: monitoring, tags: ['monitoring'] }
    - { role: deploy, tags: ['deploy'] }
