- name: Configure firewall
  ansible.builtin.import_tasks: ufw.yml

- name: Manage users
  ansible.builtin.import_tasks: users.yml

- name: Harden SSH
  ansible.builtin.import_tasks: ssh.yml

- name: Configure automatic security updates
  ansible.builtin.import_tasks: unattended.yml
