logging_enabled: false
logging_loki_url: ""
logging_loki_username: ""
logging_loki_password: ""
logging_loki_basic_auth_enabled: false
logging_promtail_http_listen_port: 9080
logging_geoip_enabled: false
logging_geoip_db_path: /etc/promtail/GeoLite2-City.mmdb
logging_collect_ufw: true
logging_nginx_access_log_path: /var/log/nginx/site.access.log
logging_nginx_error_log_path: /var/log/nginx/site.error.log
