- name: Check Nginx access log path
  ansible.builtin.stat:
    path: /var/log/nginx/access.log
  register: nginx_access_log

- name: Check Nginx error log path
  ansible.builtin.stat:
    path: /var/log/nginx/error.log
  register: nginx_error_log

- name: Set Fail2ban Nginx log availability flags
  ansible.builtin.set_fact:
    fail2ban_nginx_access_log_exists: "{{ nginx_access_log.stat.exists }}"
    fail2ban_nginx_error_log_exists: "{{ nginx_error_log.stat.exists }}"
